import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='flex justify-around bg-indigo-100 py-3'>
          <a href='/'>Home</a>
          <a href='/about'>About</a>
          <a href='/hello'>Hello</a>
        </nav>
        <div className='container mx-auto'>{children}</div>
        <footer className='text-center'>&copy; 11hertz</footer>
      </body>
    </html>
  );
}
